version: "3"
services:
  haamutech:
    command: jekyll serve
    image: jekyll/jekyll:latest
    volumes:
      - $PWD:/srv/jekyll
      - $PWD/vendor/bundle:/usr/local/bundle
      - $PWD:/usr/src/app
    ports:
      - 4000:4000
      - 35729:35729
      - 3000:3000
